# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16gTsmOVjbjYRZ22nXiUB3U9ioJicTmx4
"""

import pandas as pd
import seaborn as sns
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt
import statsmodels.stats.multicomp as mc
from scipy.stats import kurtosis, skew, bartlett
from statsmodels.formula.api import ols

MTV = pd.read_csv('https://healthdata.gov/resource/8bce-qw8w.csv')

MTV

list(MTV)

"""a factor of state we have 54 levels



"""

MTV.state.value_counts()
len(MTV['state'].value_counts())

"""a factor of collection_data we have 36 levels


"""

len(MTV.medical_neglect_only.value_counts())

"""a factor of percentage_of_inpatient_beds we have 54 levels"""

len(MTV.physical_abuse_only.value_counts())

"""one way anova

Is there a difference between state and physical_abuse_only?
"""

model = ols("physical_abuse_only ~ C(state)", data = MTV).fit()

anova_table = sm.stats.anova_lm(model, typ=1)

anova_table

"""result: no signifitcant difference

Is there a difference between state and neglect_only?
"""

model = ols("neglect_only ~ C(state)", data = MTV).fit()

anova_table = sm.stats.anova_lm(model, typ=1)

anova_table

"""result: no signifitcant difference

Is there a difference between state and multiple_maltreatment_types?
"""

model = ols("multiple_maltreatment_types ~ C(state)", data = MTV).fit()

anova_table = sm.stats.anova_lm(model, typ=1)

anova_table

"""result: no signifitcant difference

Test assumption
"""

model = ols("multiple_maltreatment_types ~ C(state)", data = MTV).fit()
stats.shapiro(model.resid)

model = ols("neglect_only ~ C(state)", data = MTV).fit()
stats.shapiro(model.resid)

model = ols("physical_abuse_only ~ C(state)", data = MTV).fit()
stats.shapiro(model.resid)